#!/bin/sh

usage() {
    printf "usage: %s [-m] name\n" $0
}

while getopts m name
do
    case $name in
    m)    master=1;;
    ?)    usage
          exit 2;;
    esac
done
shift $(($OPTIND - 1))

name=$1
if [ -z "$name" ]
then
    usage
    exit 2
fi

DIG=dig
DIGOPTS="+nocmd $name NS +noall +answer"

server=$($DIG $DIGOPTS | head -n 1 | awk '{ print $5 }')

typelist=$(nsupdate -T | awk '! /EID|NIMLOC|ATMA|UINFO|UID|GID/')

if [ -n "$master" ]
then
    # https://datatracker.ietf.org/doc/html/rfc4027#section-3
    printf '$ORIGIN %s\n' "$name" > "${name}.zone"
fi

for type in $typelist
do
    DIGOPTS="+nocmd @${server} $name $type +noall +answer"

    if [ -n "$master" ]
    then
        $DIG $DIGOPTS >> "${name}.zone"
    else
        $DIG $DIGOPTS
    fi
done
