#!/bin/sh

usage() {
    printf "usage: %s [-m] name\n" "$0" >&2
    printf "  -m    create .zone file for backup\n" >&2
}

while getopts m opt
do
    case $opt in
    m)    master=1;;
    ?)    usage
          exit 2;;
    esac
done
shift $((OPTIND - 1))

name=$1
if [ -z "$name" ]
then
    usage
    exit 2
fi

DIG=dig
DIGOPTS="+nocmd +noall +answer"

server=$(
    $DIG $DIGOPTS "$name" NS \
    | awk 'NR==1 { print $5 }'
)
rc=$?
[ $rc -ne 0 ] && exit $rc

[ -z "$server" ] && {
    printf "%s: no NS records\n" "$name" >&2
    exit 1
}

server=${server%.}.

typelist=$(nsupdate -T | awk '! /EID|NIMLOC|ATMA|RRSIG|DNSKEY|UINFO|UID|GID/')

if [ -n "$master" ]
then
    # https://datatracker.ietf.org/doc/html/rfc4027#section-3
    ZONEFILE="${name}.zone"
    printf '$ORIGIN %s.\n' "$name" > "$ZONEFILE"
    printf '$TTL 3600\n' >> "$ZONEFILE"
fi

for type in $typelist
do
    if [ -n "$master" ]
    then
        $DIG $DIGOPTS @"$server" "$name" "$type" >> "$ZONEFILE"
    else
        $DIG $DIGOPTS @"$server" "$name" "$type"
    fi
done
