#!/bin/sh

usage() {
    printf "usage: %s [-m] name\n" $0
}

while getopts m name
do
    case $name in
    m)    master=1;;
    ?)    usage
          exit 2;;
    esac
done
shift $(($OPTIND - 1))

name=$1
if [ -z "$name" ]
then
    usage
    exit 2
fi

server=$(dig +nocmd "$name" NS +noall +answer | head -n 1 | awk '{ print $5 }')

# https://gitlab.isc.org/isc-projects/bind9/-/blob/main/bin/tests/system/rrchecker/typelist.good
typelist='A
NS
MD
MF
CNAME
SOA
MB
MG
MR
NULL
WKS
PTR
HINFO
MINFO
MX
TXT
RP
AFSDB
X25
ISDN
RT
NSAP
NSAP-PTR
SIG
KEY
PX
GPOS
AAAA
LOC
NXT
SRV
NAPTR
KX
CERT
A6
DNAME
SINK
APL
DS
SSHFP
IPSECKEY
RRSIG
NSEC
DNSKEY
DHCID
NSEC3
NSEC3PARAM
TLSA
SMIMEA
HIP
NINFO
RKEY
TALINK
CDS
CDNSKEY
OPENPGPKEY
CSYNC
SPF
UNSPEC
NID
L32
L64
LP
EUI48
EUI64
URI
CAA
AVC
TA
DLV
'
DIG=dig

if [ -n "$master" ]
then
    # https://datatracker.ietf.org/doc/html/rfc4027#section-3
    printf '$ORIGIN %s\n' "$name" > "${name}.zone"
fi

for type in $typelist
do
    DIGOPTS="+nocmd @${server} $name $type +noall +answer"

    if [ -n "$master" ]
    then
        $DIG $DIGOPTS >> "${name}.zone"
    else
        $DIG $DIGOPTS
    fi
done
